SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW [dbo].[PRICING_SCENARIO_V]
 
 AS
 

SELECT  PRICING_SCENARIO_KEY
      ,PRICING_SCENARIO_ID
      ,IS_CURRENT
      ,IS_DELETED
      ,IS_CURRENT_DAY
      ,VALID_FROM
      ,VALID_TILL
      ,LAST_MODIFIED_BY
      ,LAST_MODIFIED_ON
      ,BATCH_ID
      ,LOAN_ID
      ,PIGGY_BACK_SCENARIO_ID
      ,PARENT_SCENARIO_ID
      ,LENDER_LOAN_PROGRAM_ID
      ,PRICING_GROUP_ID
      ,CREDIT_GRADE_ID
      ,INVESTOR_COMMITMENT_ID
      ,INVESTOR_STATUS_ID
      ,INV_DUE_DILIGENCE_STATUS_ID
      ,INV_DUE_DILG_SAMPLE_TYPE_ID
      ,CURRENT_PRICING_FLAG
      ,INVESTOR_LOAN_NUMBER
      ,PRICING_SCENARIO_UUID
      ,ASSG_DUE_DILG_VEND_COMPANY_ID
      ,ASSG_DUE_DILG_DATE
      ,CONDITION_NOTIFICATION_DATE
      ,SUSPENSE_EXPIRATION_DATE
      ,CALC_SUSPENSE_EXPIRATION_DATE
      ,SUSPENSE_CLEARED_DATE
      ,APPR_REVIEW_REQUEST_DATE
      ,PURCH_REVIEW_REQUEST_DATE
      ,CREDIT_REVIEW_COMPLETE_DATE
      ,COLLATERAL_REVIEW_CMPLT_DATE
      ,LEGACY_SUSP_CLEARED_DATE
      ,LEGACY_SUSP_CLEARED_FLAG
      ,LOAN_KEY
      ,PIGGY_BACK_SCENARIO_KEY
      ,PARENT_SCENARIO_KEY
      ,LENDER_LOAN_PROGRAM_KEY
      ,PRICING_GROUP_KEY
      ,CREDIT_GRADE_KEY
      ,INVESTOR_COMMITMENT_KEY
      ,INVESTOR_STATUS_KEY
      ,INV_DUE_DILIGENCE_STATUS_KEY
      ,INV_DUE_DILG_SAMPLE_TYPE_KEY
      ,ASSG_DUE_DILG_VEND_COMPANY_KEY
      ,SELLER_REVIEW_DATE
      ,[NAMESPACE]
  FROM dbo.PRICING_SCENARIO
  
  WHERE IS_CURRENT = 'Y' AND IS_DELETED = 'N'
 



GO
