SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE VIEW [dbo].[LOAN_COMMENT_v]
 
 AS
 
SELECT LOAN_COMMENT_KEY
      ,LOAN_COMMENT_ID
      ,IS_CURRENT
      ,IS_DELETED
      ,IS_CURRENT_DAY
      ,VALID_FROM
      ,VALID_TILL
      ,LAST_MODIFIED_BY
      ,LAST_MODIFIED_ON
      ,BATCH_ID
      ,LOAN_ID
      ,CONTACT_ID
      ,CREATED_DATE
      ,UPDATED_DATE
      ,SELLER_VIEWABLE_FLAG
      ,DUE_DILIGENCE_VIEWABLE_FLAG
      ,INTERNAL_VIEWABLE_FLAG
      ,COMMENT_TEXT
      ,LOAN_COMMENT_UUID
      ,LOAN_COMMENT_INDEX
      ,LOAN_COMMENT_CLASS
      ,SOURCE_IDENTIFIER
      ,DUE_DILIGENCE_VENDOR_ID
      ,SOURCE_GRADE
      ,SOURCE_COMMENTS
      ,SOURCE_DESCRIPTION
      ,SOURCE_ACKNOWLEDGED_FLAG
      ,SOURCE_DESCRIPTION_UPDATED_DATE
      ,CODE
      ,LOAN_KEY
      ,CONTACT_KEY
      ,DUE_DILIGENCE_VENDOR_KEY
      ,[NAMESPACE]
  FROM [dbo].[LOAN_COMMENT]

  
  WHERE IS_CURRENT = 'Y' AND IS_DELETED = 'N'
 


GO
