CREATE TABLE [cmt].[PRICING_SCENARIO_RATING]
(
[PRICING_SCENARIO_RATING_KEY] [numeric] (19, 0) NOT NULL IDENTITY(1, 1),
[PRICING_SCENARIO_RATING_ID] [numeric] (19, 0) NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRICING_SCENARIO_ID] [numeric] (19, 0) NULL,
[RATING_AGENCY_ID] [numeric] (19, 0) NULL,
[OVERALL_GRADE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREDIT_GRADE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPLIANCE_GRADE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROPERTY_GRADE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRICING_SCENARIO_KEY] [numeric] (19, 0) NULL,
[RATING_AGENCY_KEY] [numeric] (19, 0) NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [cmt].[PRICING_SCENARIO_RATING] ADD CONSTRAINT [pk__pricing_scenario__57a801ba] PRIMARY KEY CLUSTERED  ([PRICING_SCENARIO_RATING_KEY]) ON [PRIMARY]
GO
