CREATE TABLE [cmt].[DUE_DILG_VENDOR_DATA]
(
[DUE_DILG_VENDOR_DATA_KEY] [numeric] (19, 0) NOT NULL IDENTITY(1, 1),
[DUE_DILG_VENDOR_DATA_ID] [numeric] (19, 0) NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRICING_SCENARIO_ID] [numeric] (19, 0) NULL,
[DUE_DILG_VENDOR_STATUS_ID] [numeric] (19, 0) NULL,
[COMPANY_ID] [numeric] (19, 0) NULL,
[VENDOR_LOAN_NUMBER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDOR_STATUS_DATE] [datetime] NULL,
[VENDOR_STATUS_DATE_AS_LONG] [numeric] (19, 0) NULL,
[DUE_DILG_VENDOR_DATA_UUID] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATED_DATE] [datetime] NULL,
[UPDATED_DATE] [datetime] NULL,
[PRICING_SCENARIO_KEY] [numeric] (19, 0) NULL,
[DUE_DILG_VENDOR_STATUS_KEY] [numeric] (19, 0) NULL,
[COMPANY_KEY] [numeric] (19, 0) NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [cmt].[DUE_DILG_VENDOR_DATA] ADD CONSTRAINT [pk__due_dilg_vendor] PRIMARY KEY CLUSTERED  ([DUE_DILG_VENDOR_DATA_KEY]) ON [PRIMARY]
GO
