CREATE TABLE [dbo].[COMPANY]
(
[COMPANY_KEY] [numeric] (19, 0) NOT NULL IDENTITY(1, 1),
[COMPANY_ID] [numeric] (19, 0) NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT_DAY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALID_FROM] [datetime] NOT NULL,
[VALID_TILL] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[VERSION_NUMBER] [numeric] (19, 0) NULL,
[OWNING_COMPANY_ID] [numeric] (19, 0) NULL,
[COMPANY_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANY_CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMIN_EMAIL_TO_ADDRESS] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OWNING_COMPANY_KEY] [numeric] (19, 0) NULL,
[BUSINESS_DAY_CALENDAR_KEY] [numeric] (19, 0) NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPANY] ADD CONSTRAINT [pk__company] PRIMARY KEY CLUSTERED  ([COMPANY_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPANY] ADD CONSTRAINT [company_company] FOREIGN KEY ([OWNING_COMPANY_KEY]) REFERENCES [dbo].[COMPANY] ([COMPANY_KEY])
GO
