CREATE TABLE [dbo].[PRICING_SCENARIO]
(
[PRICING_SCENARIO_KEY] [numeric] (19, 0) NOT NULL IDENTITY(1, 1),
[PRICING_SCENARIO_ID] [numeric] (19, 0) NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT_DAY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALID_FROM] [datetime] NOT NULL,
[VALID_TILL] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[LOAN_ID] [numeric] (19, 0) NULL,
[PIGGY_BACK_SCENARIO_ID] [numeric] (19, 0) NULL,
[PARENT_SCENARIO_ID] [numeric] (19, 0) NULL,
[LENDER_LOAN_PROGRAM_ID] [numeric] (19, 0) NULL,
[PRICING_GROUP_ID] [numeric] (19, 0) NULL,
[CREDIT_GRADE_ID] [numeric] (19, 0) NULL,
[INVESTOR_COMMITMENT_ID] [numeric] (19, 0) NULL,
[INVESTOR_STATUS_ID] [numeric] (19, 0) NULL,
[INV_DUE_DILIGENCE_STATUS_ID] [numeric] (19, 0) NULL,
[INV_DUE_DILG_SAMPLE_TYPE_ID] [numeric] (19, 0) NULL,
[CURRENT_PRICING_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVESTOR_LOAN_NUMBER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SELLER_REVIEW_DATE] [datetime] NULL,
[PRICING_SCENARIO_UUID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASSG_DUE_DILG_VEND_COMPANY_ID] [numeric] (19, 0) NULL,
[ASSG_DUE_DILG_DATE] [datetime] NULL,
[CONDITION_NOTIFICATION_DATE] [datetime] NULL,
[SUSPENSE_EXPIRATION_DATE] [datetime] NULL,
[CALC_SUSPENSE_EXPIRATION_DATE] [datetime] NULL,
[SUSPENSE_CLEARED_DATE] [datetime] NULL,
[APPR_REVIEW_REQUEST_DATE] [datetime] NULL,
[PURCH_REVIEW_REQUEST_DATE] [datetime] NULL,
[CREDIT_REVIEW_COMPLETE_DATE] [datetime] NULL,
[COLLATERAL_REVIEW_CMPLT_DATE] [datetime] NULL,
[LEGACY_SUSP_CLEARED_DATE] [datetime] NULL,
[LEGACY_SUSP_CLEARED_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAN_KEY] [numeric] (19, 0) NULL,
[PIGGY_BACK_SCENARIO_KEY] [numeric] (19, 0) NULL,
[PARENT_SCENARIO_KEY] [numeric] (19, 0) NULL,
[LENDER_LOAN_PROGRAM_KEY] [numeric] (19, 0) NULL,
[PRICING_GROUP_KEY] [numeric] (19, 0) NULL,
[CREDIT_GRADE_KEY] [numeric] (19, 0) NULL,
[INVESTOR_COMMITMENT_KEY] [numeric] (19, 0) NULL,
[INVESTOR_STATUS_KEY] [numeric] (19, 0) NULL,
[INV_DUE_DILIGENCE_STATUS_KEY] [numeric] (19, 0) NULL,
[INV_DUE_DILG_SAMPLE_TYPE_KEY] [numeric] (19, 0) NULL,
[ASSG_DUE_DILG_VEND_COMPANY_KEY] [numeric] (19, 0) NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRICING_SCENARIO] ADD CONSTRAINT [pk__pricing_scenario] PRIMARY KEY CLUSTERED  ([PRICING_SCENARIO_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [pricing_scenario_idx1] ON [dbo].[PRICING_SCENARIO] ([INVESTOR_LOAN_NUMBER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [pricing_scenario_fk1] ON [dbo].[PRICING_SCENARIO] ([LOAN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [pricing_scenario_idx_uuid] ON [dbo].[PRICING_SCENARIO] ([PRICING_SCENARIO_UUID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRICING_SCENARIO] ADD CONSTRAINT [pricing_scenario_inv_due_diligence_status] FOREIGN KEY ([INV_DUE_DILIGENCE_STATUS_KEY]) REFERENCES [dbo].[INV_DUE_DILIGENCE_STATUS] ([INV_DUE_DILIGENCE_STATUS_KEY])
GO
ALTER TABLE [dbo].[PRICING_SCENARIO] ADD CONSTRAINT [pricing_scenario_investor_status] FOREIGN KEY ([INVESTOR_STATUS_KEY]) REFERENCES [dbo].[INVESTOR_STATUS] ([INVESTOR_STATUS_KEY])
GO
ALTER TABLE [dbo].[PRICING_SCENARIO] ADD CONSTRAINT [pricing_scenario_loan] FOREIGN KEY ([LOAN_KEY]) REFERENCES [dbo].[LOAN] ([LOAN_KEY])
GO
ALTER TABLE [dbo].[PRICING_SCENARIO] ADD CONSTRAINT [pricing_scenario_parent_scenario_key] FOREIGN KEY ([PARENT_SCENARIO_KEY]) REFERENCES [dbo].[PRICING_SCENARIO] ([PRICING_SCENARIO_KEY])
GO
ALTER TABLE [dbo].[PRICING_SCENARIO] ADD CONSTRAINT [pricing_scenario_piggy_back_scenario_key] FOREIGN KEY ([PIGGY_BACK_SCENARIO_KEY]) REFERENCES [dbo].[PRICING_SCENARIO] ([PRICING_SCENARIO_KEY])
GO
