CREATE TABLE [dbo].[ACTIVITY_COMMENT]
(
[ACTIVITY_COMMENT_KEY] [numeric] (19, 0) NOT NULL IDENTITY(1, 1),
[ACTIVITY_COMMENT_ID] [numeric] (19, 0) NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT_DAY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALID_FROM] [datetime] NOT NULL,
[VALID_TILL] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[ACTIVITY_ID] [numeric] (19, 0) NULL,
[CONTACT_ID] [numeric] (19, 0) NULL,
[CREATED_DATE] [datetime] NULL,
[UPDATED_DATE] [datetime] NULL,
[SELLER_VIEWABLE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUE_DILIGENCE_VIEWABLE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INTERNAL_VIEWABLE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMMENT_TEXT] [varchar] (2048) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVITY_COMMENT_UUID] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVITY_COMMENT_INDEX] [int] NULL,
[ACTIVITY_KEY] [numeric] (19, 0) NULL,
[CONTACT_KEY] [numeric] (19, 0) NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTIVITY_COMMENT] ADD CONSTRAINT [pk__activity_comment] PRIMARY KEY CLUSTERED  ([ACTIVITY_COMMENT_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [activity_comment_idx_uuid] ON [dbo].[ACTIVITY_COMMENT] ([ACTIVITY_COMMENT_UUID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [activity_comment_fk1] ON [dbo].[ACTIVITY_COMMENT] ([ACTIVITY_ID], [ACTIVITY_COMMENT_INDEX]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTIVITY_COMMENT] ADD CONSTRAINT [activity_comment_activity] FOREIGN KEY ([ACTIVITY_KEY]) REFERENCES [dbo].[ACTIVITY] ([ACTIVITY_KEY])
GO
ALTER TABLE [dbo].[ACTIVITY_COMMENT] ADD CONSTRAINT [activity_comment_condition] FOREIGN KEY ([ACTIVITY_KEY]) REFERENCES [dbo].[CONDITION] ([ACTIVITY_KEY])
GO
