CREATE TABLE [dbo].[END_USER]
(
[CONTACT_KEY] [numeric] (19, 0) NOT NULL IDENTITY(1, 1),
[CONTACT_ID] [numeric] (19, 0) NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT_DAY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALID_FROM] [datetime] NOT NULL,
[VALID_TILL] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[COMPANY_ID] [numeric] (19, 0) NULL,
[USER_NAME] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNT_APPROVED_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNT_ACTIVATED_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANY_KEY] [numeric] (19, 0) NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[END_USER] ADD CONSTRAINT [pk__end_user__02fc7413] PRIMARY KEY CLUSTERED  ([CONTACT_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[END_USER] ADD CONSTRAINT [end_user_company] FOREIGN KEY ([COMPANY_KEY]) REFERENCES [dbo].[COMPANY] ([COMPANY_KEY])
GO
