CREATE TABLE [dbo].[CONDITION]
(
[ACTIVITY_KEY] [numeric] (19, 0) NOT NULL IDENTITY(1, 1),
[ACTIVITY_ID] [numeric] (19, 0) NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT_DAY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALID_FROM] [datetime] NOT NULL,
[VALID_TILL] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[CONDITION_TYPE_ID] [numeric] (19, 0) NULL,
[INVESTOR_CONDITION_STATUS_ID] [numeric] (19, 0) NULL,
[DUE_DILG_VEND_COND_STATUS_ID] [numeric] (19, 0) NULL,
[CONDITION_STATUS_ID] [numeric] (19, 0) NULL,
[CONDITION_TIMING_TYPE_ID] [numeric] (19, 0) NULL,
[SOURCE_GRADE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_COMMENTS] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVESTOR_CONDITION_STATUS_KEY] [numeric] (19, 0) NULL,
[DUE_DILG_VEND_COND_STATUS_KEY] [numeric] (19, 0) NULL,
[CONDITION_STATUS_KEY] [numeric] (19, 0) NULL,
[CONDITION_TIMING_TYPE_KEY] [numeric] (19, 0) NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONDITION] ADD CONSTRAINT [pk__condition] PRIMARY KEY CLUSTERED  ([ACTIVITY_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CONDITION_ACTIVITY_ID] ON [dbo].[CONDITION] ([ACTIVITY_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [condition_idx2] ON [dbo].[CONDITION] ([CONDITION_STATUS_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [condition_idx1] ON [dbo].[CONDITION] ([INVESTOR_CONDITION_STATUS_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CONDITION_Namespace] ON [dbo].[CONDITION] ([NAMESPACE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONDITION] ADD CONSTRAINT [condition_investor_condition_status] FOREIGN KEY ([INVESTOR_CONDITION_STATUS_KEY]) REFERENCES [dbo].[INVESTOR_CONDITION_STATUS] ([INVESTOR_CONDITION_STATUS_KEY])
GO
