CREATE TABLE [dbo].[LOAN_COMMENT]
(
[LOAN_COMMENT_KEY] [numeric] (19, 0) NOT NULL IDENTITY(1, 1),
[LOAN_COMMENT_ID] [numeric] (19, 0) NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT_DAY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALID_FROM] [datetime] NOT NULL,
[VALID_TILL] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[LOAN_ID] [numeric] (19, 0) NULL,
[CONTACT_ID] [numeric] (19, 0) NULL,
[CREATED_DATE] [datetime] NULL,
[UPDATED_DATE] [datetime] NULL,
[SELLER_VIEWABLE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUE_DILIGENCE_VIEWABLE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INTERNAL_VIEWABLE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMMENT_TEXT] [varchar] (2048) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAN_COMMENT_UUID] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAN_COMMENT_INDEX] [int] NULL,
[LOAN_COMMENT_CLASS] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_IDENTIFIER] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUE_DILIGENCE_VENDOR_ID] [numeric] (19, 0) NULL,
[SOURCE_GRADE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_COMMENTS] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_DESCRIPTION] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ACKNOWLEDGED_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_DESCRIPTION_UPDATED_DATE] [datetime] NULL,
[CODE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAN_KEY] [numeric] (19, 0) NULL,
[CONTACT_KEY] [numeric] (19, 0) NULL,
[DUE_DILIGENCE_VENDOR_KEY] [numeric] (19, 0) NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COMMENT] ADD CONSTRAINT [pk__loan_comment] PRIMARY KEY CLUSTERED  ([LOAN_COMMENT_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOAN_COMMENT] ADD CONSTRAINT [loan_comment_loan] FOREIGN KEY ([LOAN_KEY]) REFERENCES [dbo].[LOAN] ([LOAN_KEY])
GO
