CREATE TABLE [dbo].[HISTORY_EVENT]
(
[HISTORY_EVENT_KEY] [numeric] (19, 0) NOT NULL IDENTITY(1, 1),
[HISTORY_EVENT_ID] [numeric] (19, 0) NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT_DAY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALID_FROM] [datetime] NOT NULL,
[VALID_TILL] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[LOAN_ID] [numeric] (19, 0) NULL,
[CONTACT_ID] [numeric] (19, 0) NULL,
[CHANGE_DATE] [datetime] NULL,
[EVENT_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID_BEFORE] [numeric] (19, 0) NULL,
[VALUE_BEFORE] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID_AFTER] [numeric] (19, 0) NULL,
[VALUE_AFTER] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDITIONAL_INFORMATION] [varchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHANGE_BY_DETAIL] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VERBOSE_HISTORY_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOAN_KEY] [numeric] (19, 0) NULL,
[CONTACT_KEY] [numeric] (19, 0) NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORY_EVENT] ADD CONSTRAINT [pk__history_event__43d61337] PRIMARY KEY CLUSTERED  ([HISTORY_EVENT_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORY_EVENT] ADD CONSTRAINT [history_event_loan] FOREIGN KEY ([LOAN_KEY]) REFERENCES [dbo].[LOAN] ([LOAN_KEY])
GO
GRANT SELECT ON  [dbo].[HISTORY_EVENT] TO [report_user]
GO
GRANT INSERT ON  [dbo].[HISTORY_EVENT] TO [report_user]
GO
GRANT UPDATE ON  [dbo].[HISTORY_EVENT] TO [report_user]
GO
