CREATE TABLE [lms].[Company]
(
[Company_Key] [bigint] NOT NULL IDENTITY(1, 1),
[ID] [numeric] (10, 0) NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameAlt] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Website] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FtpSite] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [xml] NULL,
[Username] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Timestamp] [datetime] NULL,
[IsBrokerFlag] [int] NULL,
[IsBankFlag] [int] NULL,
[IsWHLenderFlag] [int] NULL,
[EmailPattern] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterID] [numeric] (10, 0) NULL,
[Category] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDealerFlag] [int] NULL,
[IsServicerFlag] [int] NULL,
[CorpType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountyFilingDt] [datetime] NULL,
[FDICCertNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FedTaxID] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalYearEnd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncorporationDt] [datetime] NULL,
[OTCDocketNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PubliclyTradedFlag] [int] NULL,
[PubliclyTradedTicker] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateFilingDt] [datetime] NULL,
[YearEstablished] [int] NULL,
[IsBuyerFlag] [int] NULL,
[IsTrusteeFlag] [int] NULL,
[IsInvestorFlag] [int] NULL,
[IsSellerFlag] [int] NULL,
[PrimaryContactID] [numeric] (10, 0) NULL,
[SalesRepID] [numeric] (10, 0) NULL,
[SalesMgrID] [numeric] (10, 0) NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusDetail] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDAlt] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Terms] [xml] NULL,
[IsCustodianFlag] [int] NULL,
[UsernameAsOf] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimestampAsOf] [datetime] NULL,
[OpportunitySize] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MktSegment] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryRole] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tags] [xml] NULL,
[Background] [xml] NULL,
[Tagline] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Industry] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourcingMethod] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourcingDetail] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Logo] [varbinary] (max) NULL,
[LogoWithTagline] [varbinary] (max) NULL,
[LogoWithName] [varbinary] (max) NULL,
[Viability] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ViabilityReportDt] [datetime] NULL,
[DataSourceAsOf] [datetime] NULL,
[IsProviderFlag] [int] NULL,
[NotificationRateSheet] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NotificationLock] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NotificationFunding] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsEntityFlag] [int] NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [lms].[Company] ADD CONSTRAINT [pk__lms_company] PRIMARY KEY CLUSTERED  ([Company_Key]) ON [PRIMARY]
GO
