CREATE TABLE [lms].[Loan]
(
[Loan_Key] [bigint] NOT NULL IDENTITY(1, 1),
[Loan_ID] [numeric] (10, 0) NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OwnerLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellerID] [numeric] (10, 0) NULL,
[SellerLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [xml] NULL,
[ServicerLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OwnerID] [numeric] (10, 0) NULL,
[ServicerID] [numeric] (10, 0) NULL,
[CustodianID] [numeric] (10, 0) NULL,
[CustodianLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MERSLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicerIDInterim] [numeric] (10, 0) NULL,
[TrusteeID] [numeric] (10, 0) NULL,
[TrusteeLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WHLenderID] [numeric] (10, 0) NULL,
[WHLenderLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FnMaeLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FHAVACertNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellerLoanTag] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FundProviderID] [numeric] (10, 0) NULL,
[StatusDetail] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatasourceINS] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UsernameINS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TimestampINS] [datetime] NOT NULL,
[Datasource] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Username] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Timestamp] [datetime] NULL,
[MatchKey] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicerIDMaster] [numeric] (10, 0) NULL,
[ServicerIDPrimary] [numeric] (10, 0) NULL,
[LoanIDCombo] [numeric] (10, 0) NULL,
[SellerLoanIDTape] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackOfficeLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerLoanIDTape] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicerLoanIDTape] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BackOfficeLoanIDTape] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicerLoanIDInterim] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceMarked] [float] NULL,
[SellDt] [datetime] NULL,
[Broker] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MersMOMFlag] [int] NULL,
[NonSourcableFlag] [int] NULL,
[NonSourcableReason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicerLoanIDPrimary] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicerLoanIDMaster] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSIP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSIPPrev] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSIPStlDt] [datetime] NULL,
[TradAccnt] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TradAccntPrev] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TradAccntStlDt] [datetime] NULL,
[LatestTransDt] [datetime] NULL,
[LatestTransType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusOverride] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusDetailOverride] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanOfficer] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Processor] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Underwriter] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Closer] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceMarkedDt] [datetime] NULL,
[LPLoanID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginatorLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginatorID] [numeric] (10, 0) NULL,
[InternalRiskScore] [float] NULL,
[AssetClass] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellerNoteID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountMgr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicerNamePrev] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelatedLoanID1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelatedLoanID2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelatedLoanID3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelatedLoanID4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelatedLoanID5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WHLenderTape] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActiveFlag] [int] NULL,
[SellerLoanIDAlt] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InventoryStatusAlt] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tags] [xml] NULL,
[SellerLoanIDPrior] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvancePct] [float] NULL,
[FinancingRtMargin] [float] NULL,
[AssetSoldNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusTape] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestTransMethod] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Strategy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecuritizationLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BrokerID] [numeric] (10, 0) NULL,
[BrokerLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MERSFlag] [int] NULL,
[PartialRollIndicatorStr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanOfficerID] [numeric] (10, 0) NULL,
[SvcTransmissionDtLegacy] [datetime] NULL,
[SRPAtSaleLegacy] [float] NULL,
[DocShipDtLegacy] [datetime] NULL,
[PurchByInvestorDtLegacy] [datetime] NULL,
[MBSPoolIssueDtLegacy] [datetime] NULL,
[CustDocShipDtLegacy] [datetime] NULL,
[RepurchDtLegacy] [datetime] NULL,
[MBSPoolNum] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [lms].[Loan] ADD CONSTRAINT [pk_loan] PRIMARY KEY CLUSTERED  ([Loan_Key]) ON [PRIMARY]
GO
