CREATE TABLE [lms].[svCCEx]
(
[svCCEx_Key] [bigint] NOT NULL IDENTITY(1, 1),
[svCCEx_ID] [numeric] (10, 0) NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[svCCID] [numeric] (10, 0) NOT NULL,
[Code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StatusDetail] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsOfDt] [datetime] NOT NULL,
[Severity] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueOrig] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueRevised] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reviewer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [xml] NULL,
[Datasource] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Username] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Timestamp] [datetime] NULL,
[DocTypeID] [numeric] (10, 0) NOT NULL,
[Issue] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IssueVendor] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CloseDt] [datetime] NULL,
[FirstReportedDt] [datetime] NULL,
[LastReportedDt] [datetime] NULL,
[DocCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConCodeDesc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocNotes] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReleaseReason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysAtVendor] [int] NULL,
[String01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[String02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocLocation] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [lms].[svCCEx] ADD CONSTRAINT [pk_svccex] PRIMARY KEY CLUSTERED  ([svCCEx_Key]) ON [PRIMARY]
GO
