CREATE TABLE [lms].[svCC]
(
[svCC_Key] [bigint] NOT NULL IDENTITY(1, 1),
[LoanID] [numeric] (10, 0) NOT NULL,
[ProviderID] [numeric] (10, 0) NULL,
[OrderID] [numeric] (10, 0) NULL,
[BATCH_ID] [bigint] NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AsOfDt] [datetime] NULL,
[Action] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResponsibleParty] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusDetail] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [xml] NULL,
[Datasource] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MatchKey] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Username] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Timestamp] [datetime] NULL,
[AmortType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConvertibleFlag] [int] NULL,
[CustodianLoanID] [int] NULL,
[LoanType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaturityDt] [datetime] NULL,
[MERSLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MersMOMFlag] [int] NULL,
[NegamLimitPct] [float] NULL,
[OriginationDt] [datetime] NULL,
[PmtCapPeriodic] [float] NULL,
[PmtCapRecast] [float] NULL,
[PmtDueDtFirst] [datetime] NULL,
[PmtOrig] [float] NULL,
[PmtResetDtFirst] [datetime] NULL,
[PmtResetFrequency] [float] NULL,
[PmtResetFrequency2nd] [float] NULL,
[PrepayPenaltyTerm] [float] NULL,
[RtCapFirst] [float] NULL,
[RtCapLife] [float] NULL,
[RtCapPeriodic] [float] NULL,
[RtFloorPeriodic] [float] NULL,
[RtIndex] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtLookbackPeriod] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtMargin] [float] NULL,
[RtOrig] [float] NULL,
[RtResetDtFirst] [datetime] NULL,
[RtResetFrequency] [int] NULL,
[RtResetFrequency2nd] [float] NULL,
[RtRoundingMethod] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermIOOrig] [int] NULL,
[TermOrig] [int] NULL,
[City] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BalOrig] [float] NULL,
[Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameFirst] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLast] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileCheckInDt] [datetime] NULL,
[FileCheckOutDt] [datetime] NULL,
[DefectsFlag] [int] NULL,
[FileRcvdFrom] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileRcvdDt] [datetime] NULL,
[FileSentTo] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileSentDt] [datetime] NULL,
[FileLocation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModificationDt] [datetime] NULL,
[PkgCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtMinLife] [float] NULL,
[RtRoundingFactor] [float] NULL,
[SellerLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrepayPenaltyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrepayPenaltyFactor] [float] NULL,
[PrepayPenaltyStr] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrepayPenaltyTermHard] [float] NULL,
[PrepayPenaltyTermSoft] [float] NULL,
[PrepayPenaltyType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModificationType] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtFloorFirst] [float] NULL,
[MECAFlag] [int] NULL,
[svCC_ID] [numeric] (10, 0) NULL,
[AdvanceAmt] [float] NULL,
[AppraisalValue] [float] NULL,
[BalCurr] [float] NULL,
[BalloonFlag] [int] NULL,
[ConversionDtFirst] [datetime] NULL,
[ConversionEndDt] [datetime] NULL,
[ConversionMargin] [float] NULL,
[County] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeliveryDt] [datetime] NULL,
[DocTypeID] [numeric] (10, 0) NULL,
[LTV] [float] NULL,
[NameFirstCb] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLastCb] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NegAmFlag] [int] NULL,
[Occupancy] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaidToDt] [datetime] NULL,
[PmtCurr] [float] NULL,
[PmtDueDtNext] [datetime] NULL,
[PmtResetDtNext] [datetime] NULL,
[ProductType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purpose] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtCurr] [float] NULL,
[RtFloorLife] [float] NULL,
[RtIndexValCurr] [float] NULL,
[RtIndexValFirst] [float] NULL,
[RtResetDtNext] [datetime] NULL,
[TermAmortOrig] [int] NULL,
[ReviewType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Mortgage] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Note] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PowerOfAttorney] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Assignment] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Endorsement] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterveningAssignment] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterveningAssignment2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterveningEndorsement] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterveningEndorsement2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PoolNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PoolType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicerCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvestorLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusReleased] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MERSMinLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CodeReleased] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReleaseDt] [date] NULL,
[Stage] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActiveFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CloseDt] [date] NULL,
[CaseNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrustNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ControlNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicerLoanID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaxRtChg] [float] NULL,
[IOFlag] [int] NULL,
[IntAmt] [float] NULL,
[MERSFlag] [int] NULL,
[BookPage] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InstrumentNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordedDt] [datetime] NULL,
[PrePayPenaltyFlag] [int] NULL,
[String01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[String02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date01] [datetime] NULL,
[Date02] [datetime] NULL,
[Float01] [float] NULL,
[Float02] [float] NULL,
[Float03] [float] NULL,
[Float04] [float] NULL,
[Int01] [int] NULL,
[Int02] [int] NULL,
[BalloonTerm] [int] NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [lms].[svCC] ADD CONSTRAINT [pk_svcc] PRIMARY KEY CLUSTERED  ([svCC_Key]) ON [PRIMARY]
GO
