CREATE TABLE [lms].[svDD]
(
[svDD_Key] [bigint] NOT NULL IDENTITY(1, 1),
[LoanID] [numeric] (10, 0) NOT NULL,
[ProviderID] [numeric] (10, 0) NOT NULL,
[OrderID] [numeric] (10, 0) NULL,
[BATCH_ID] [bigint] NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AsOfDt] [datetime] NOT NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StatusDetail] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSIP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLast] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalDt] [datetime] NULL,
[AppraisalSystem] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalValue] [float] NULL,
[AssumableFlag] [int] NULL,
[BalCurr] [float] NULL,
[BalLienJunior] [float] NULL,
[BalLienSenior] [float] NULL,
[BalloonFlag] [int] NULL,
[BalOrig] [float] NULL,
[CreditGrade] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BuyDownFlag] [int] NULL,
[CashOutAmt] [float] NULL,
[CashOutUse] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLTV] [float] NULL,
[ConversionPeriod] [float] NULL,
[ConvertibleFlag] [int] NULL,
[ConvertibleType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DelqDays] [int] NULL,
[DocType] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSIFlag] [int] NULL,
[DTI] [float] NULL,
[EmploymentLength] [float] NULL,
[OverallEventLevel] [int] NULL,
[ComplianceLevel] [int] NULL,
[CreditLevel] [int] NULL,
[FICO] [int] NULL,
[FICOcb] [int] NULL,
[PmtDueDtFirst] [datetime] NULL,
[IncomeGross] [float] NULL,
[LeaseholdFlag] [int] NULL,
[LienPosition] [int] NULL,
[LoanType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtLookbackPeriod] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTV] [float] NULL,
[LTVCurr] [float] NULL,
[RtMargin] [float] NULL,
[RtIndex] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaturityDt] [datetime] NULL,
[PMICompany] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PMICoverage] [float] NULL,
[PMIFee] [float] NULL,
[PMIType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameFirst] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameFirstcb] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLastcb] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NegamFlag] [int] NULL,
[NegamLimitPct] [float] NULL,
[Units] [int] NULL,
[Occupancy] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginationDt] [datetime] NULL,
[Originator] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaidToDt] [datetime] NULL,
[PayHistory] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtCurr] [float] NULL,
[PmtOrig] [float] NULL,
[PmtPITI] [float] NULL,
[PmtTI] [float] NULL,
[PrepayPenaltyPeriod] [float] NULL,
[PrepayPenaltyStr] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverallReason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComplianceReason] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditReason] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purpose] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtResetDtFirst] [datetime] NULL,
[RtResetDtNext] [datetime] NULL,
[RtResetFrequency] [int] NULL,
[RtRoundingFactor] [float] NULL,
[RtRoundingMethod] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtCapFirst] [float] NULL,
[RtMaxLife] [float] NULL,
[RtCapPeriodic] [float] NULL,
[RtCurr] [float] NULL,
[RtMinLife] [float] NULL,
[RtOrig] [float] NULL,
[SalePrice] [float] NULL,
[Section32Flag] [int] NULL,
[Section32Status] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelfEmployedFlag] [int] NULL,
[Seller] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SvcFee] [float] NULL,
[SimSecondFlag] [int] NULL,
[SSN] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSNcb] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermAmortOrig] [int] NULL,
[TermOrig] [int] NULL,
[TexasCashoutFlag] [int] NULL,
[Zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PMICertNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForeignNationalFlag] [int] NULL,
[MHLandOwnedFlag] [int] NULL,
[MHUsedFlag] [int] NULL,
[MHWidth] [int] NULL,
[MHYear] [int] NULL,
[MSA] [int] NULL,
[SilentSecondFlag] [int] NULL,
[FnMaeDUCaseID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FnMaeDURec] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UWGuidelineCompliantFlag] [int] NULL,
[FnMaeFeeCompliantFlag] [int] NULL,
[DocTypeSNP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalTypeSNP] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLTVCurr] [float] NULL,
[Servicer] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtCapLife] [float] NULL,
[IncomeDisposable] [float] NULL,
[Reserves] [float] NULL,
[FirstTimeBuyerFlag] [int] NULL,
[RtResetPmtShock] [float] NULL,
[BankruptcyFlag] [int] NULL,
[ForeclosureFlag] [int] NULL,
[BorrAddress] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrCity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrState] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrZip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UWGuidelineUsed] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetVerifFlagSNP] [int] NULL,
[PropertyTypeSNP] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanTypeSNP] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermIOOrig] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompensatingFactors] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExceptionNotes] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [xml] NULL,
[Datasource] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Username] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Timestamp] [datetime] NULL,
[ELTV] [float] NULL,
[Employer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetsPledged] [float] NULL,
[MatchKey] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtResetDtFirst] [datetime] NULL,
[RtIndexValFirst] [float] NULL,
[PmtCapPeriodic] [float] NULL,
[RtFloorPeriodic] [float] NULL,
[PmtResetFrequency] [int] NULL,
[CashOutAmtNet] [float] NULL,
[ClosingCosts] [float] NULL,
[PhoneHome] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneWork] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmortType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CensusTract] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterestCollType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtFrequency] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RuralFlag] [int] NULL,
[PhoneHomeCb] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneWorkCb] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtAdjustableFlag] [int] NULL,
[CreditGradeLMS] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrRemAssets] [float] NULL,
[BalSched] [float] NULL,
[BorrPriorBKChapter] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FHCondoClass] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrPriorFCFlag] [int] NULL,
[BorrPriorBKDischDt] [datetime] NULL,
[BorrPriorBKFilingDt] [datetime] NULL,
[BorrPriorFCDt] [datetime] NULL,
[BorrPriorDelq30NR] [int] NULL,
[BorrPriorDelq30] [int] NULL,
[BorrPriorDelq60NR] [int] NULL,
[BorrPriorDelq60] [int] NULL,
[BorrPriorDelq90NR] [int] NULL,
[BorrPriorDelq90] [int] NULL,
[LateChgCalcType] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LateChgCalcDays] [int] NULL,
[LateChgCalcPct] [float] NULL,
[BorrPriorBKFlag] [int] NULL,
[SecFinFlag] [int] NULL,
[TILAPR] [float] NULL,
[TILPrepayNoticeFlag] [int] NULL,
[SellerResponse] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorAsOfDt] [datetime] NULL,
[PriorComplianceLevel] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorComplianceReason] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorCreditLevel] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorCreditReason] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditExceptions] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComplianceExceptions] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComplianceComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorOverallEventLevel] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorOverallReason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HUD1Reductions] [float] NULL,
[PtsAndFeesAPR] [float] NULL,
[PtsAndFeesSec32] [float] NULL,
[PtsAndFeesState] [float] NULL,
[Sec32Yield] [float] NULL,
[TILAmtFinanced] [float] NULL,
[TILFinCharges] [float] NULL,
[TILRtAdjustableFlag] [int] NULL,
[Reviewer] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FloodZoneCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeGrosscb] [float] NULL,
[String01] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[String02] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[String03] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[String04] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[String05] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[String06] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Float01] [float] NULL,
[Float02] [float] NULL,
[Float03] [float] NULL,
[Float04] [float] NULL,
[Float05] [float] NULL,
[Float06] [float] NULL,
[Date01] [datetime] NULL,
[Date02] [datetime] NULL,
[Date03] [datetime] NULL,
[WillingnessToRepay] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbilityToRepay] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReasonForDefault] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Resolution] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResolutionDetails] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnershipYears] [float] NULL,
[svDD_ID] [numeric] (10, 0) NULL,
[CollateralLevel] [int] NULL,
[CollateralReason] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralExceptions] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmortTypeMod] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BalEscrowAdv] [float] NULL,
[BalOrigMod] [float] NULL,
[BalSuspense] [float] NULL,
[BKCaseID] [numeric] (10, 0) NULL,
[BKComments] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKMFRFilingDt] [datetime] NULL,
[BKStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CFVel12Month] [float] NULL,
[CFVel3Month] [float] NULL,
[CFVel6Month] [float] NULL,
[CFVel9Month] [float] NULL,
[CollectionComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditCurrentDt] [datetime] NULL,
[DateMod] [datetime] NULL,
[DelqFlag] [int] NULL,
[EvidenceEquityAnalysisFlag] [int] NULL,
[FBCurr] [float] NULL,
[FBPlanOnTargetFlag] [int] NULL,
[FBStartDt] [datetime] NULL,
[FCComment] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCNumDaysIn] [int] NULL,
[FCNumDaysRem] [int] NULL,
[FCStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCStatusDt] [datetime] NULL,
[FICOcbCurr] [int] NULL,
[FICOcurr] [int] NULL,
[FICODt] [datetime] NULL,
[FlagMod] [int] NULL,
[GoodFaithStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IOFlag] [int] NULL,
[IsPMIRequired] [int] NULL,
[LienSeniorFCFlag] [int] NULL,
[LitigationFlag] [int] NULL,
[LMComments] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaturityDtMod] [datetime] NULL,
[MfrObtainedFlag] [int] NULL,
[OtherAdvAmt] [float] NULL,
[PayHistoryLength] [int] NULL,
[PerformingFlag] [int] NULL,
[PmtDueDtFirstMod] [datetime] NULL,
[PmtEscrow] [float] NULL,
[PmtFrequencyMod] [float] NULL,
[PmtOrigMod] [float] NULL,
[PmtResetDtFirstMod] [int] NULL,
[PmtResetDtNext] [datetime] NULL,
[PmtResetDtNextMod] [datetime] NULL,
[PmtResetFrequencyMod] [int] NULL,
[AcqPoolID] [int] NULL,
[PrepayFlag] [int] NULL,
[PriorPayHistory] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductTypeMod] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyCondition] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyConditionCurr] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReasonMod] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReliefDt] [datetime] NULL,
[REOFlag] [int] NULL,
[RePerformingFlag] [int] NULL,
[RightRescissionStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtCapPeriodicMod] [float] NULL,
[RtIndexMod] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtMarginMod] [float] NULL,
[RtMaxFirst] [float] NULL,
[RtMaxFirstMod] [float] NULL,
[RtMaxLifeMod] [float] NULL,
[RtMinFirst] [float] NULL,
[RtMinFirstMod] [float] NULL,
[RtMinLifeMod] [float] NULL,
[RtOrigMod] [float] NULL,
[RtResetDtFirstMod] [datetime] NULL,
[RtResetDtNextMod] [datetime] NULL,
[RtResetFrequencyMod] [float] NULL,
[ServicerHelloLtrSentFlag] [int] NULL,
[SkipTracingFlag] [int] NULL,
[SurplusFundsClaimFlag] [int] NULL,
[SurplusFundsGenFlag] [int] NULL,
[TapeExceptions] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermAmortOrigMod] [float] NULL,
[TermOrigMod] [int] NULL,
[TypeMod] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueCurrent] [float] NULL,
[ValueCurrentDt] [datetime] NULL,
[PriorCollateralLevel] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorCollateralReason] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditGradeMoodys] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralGradeMoodys] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComplianceGradeMoodys] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditGradeSandP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralGradeSandP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComplianceGradeSandP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditGradeFitch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralGradeFitch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComplianceGradeFitch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorCreditGradeMoodys] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorCollateralGradeMoodys] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorComplianceGradeMoodys] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorCreditGradeSandP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorCollateralGradeSandP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorComplianceGradeSandP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorCreditGradeFitch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorCollateralGradeFitch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorComplianceGradeFitch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverallLevelVendor] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditLevelVendor] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralLevelVendor] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComplianceLevelVendor] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverallGradeMoodys] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverallGradeFitch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverallGradeSandP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorOverallGradeMoodys] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorOverallGradeFitch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorOverallGradeSandP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsernameAsOf] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TimestampAsOf] [datetime] NOT NULL,
[UsernameINS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TimestampINS] [datetime] NOT NULL,
[TimestampAsOfVendor] [datetime] NULL,
[CommentsText] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidency] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyCb] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyCb2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyCb3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginationChannel] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QMType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EscrowType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetsTotal] [float] NULL,
[MonthReserves] [float] NULL,
[FICOCb2] [int] NULL,
[FICOCb3] [int] NULL,
[HelocFlag] [int] NULL,
[ClosingPoints] [float] NULL,
[HighCostFlag] [int] NULL,
[RelocationFlag] [int] NULL,
[BrokerFlag] [int] NULL,
[EscrowFlag] [int] NULL,
[LoanTypeSenior] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtResetMoFirstSenior] [int] NULL,
[NegAmLimitPctSenior] [float] NULL,
[OriginationDtSenior] [datetime] NULL,
[BuyDownTerm] [float] NULL,
[TermDraw] [int] NULL,
[PayStatusMBA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TeaserTerm] [int] NULL,
[RtFloorFirst] [float] NULL,
[RtResetMoNext] [float] NULL,
[NegamRecastMosFirst] [int] NULL,
[NegamRecastMosPeriodic] [int] NULL,
[PmtResetFrequency2nd] [int] NULL,
[PmtCapFirst] [float] NULL,
[PmtMinResetFrequencyFirst] [int] NULL,
[PmtMinResetFrequency] [int] NULL,
[PmtOptionFlag] [int] NULL,
[RecastOptions] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtAmtMinFirst] [float] NULL,
[PmtAmtMin] [float] NULL,
[PrepayPenaltyCalc] [int] NULL,
[PrepayPenaltyType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrepayPenaltyTerm] [float] NULL,
[PrepayPenaltyTermHard] [float] NULL,
[NumPropertiesInv] [int] NULL,
[NumBorrowers] [int] NULL,
[PmtCurrOther] [float] NULL,
[EmploymentLengthCb] [float] NULL,
[YearsAtResidence] [float] NULL,
[FICOModelType1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICOCurrDt] [date] NULL,
[FICO1] [int] NULL,
[FICO1Cb] [int] NULL,
[FICO2] [int] NULL,
[FICO2Cb] [int] NULL,
[FICO3] [int] NULL,
[FICO3Cb] [int] NULL,
[FICOMethodCurr] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VantageScore] [int] NULL,
[VantageScoreCb] [int] NULL,
[VantageScoreMethod] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VantageScoreDt] [date] NULL,
[TradeLineCnt] [int] NULL,
[TradeLineMaxAmt] [float] NULL,
[TradeLineMaxLength] [int] NULL,
[CreditLineUsageRatio] [float] NULL,
[PriorBKMos] [int] NULL,
[PriorFCMos] [int] NULL,
[Form4506TFlag] [int] NULL,
[IncomeVerifLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeVerifLevelCb] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentVerifType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentVerifTypeCb] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetVerifLevel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetVerifLevelCb] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CashReserves] [float] NULL,
[IncomeOther] [float] NULL,
[IncomeOtherCb] [float] NULL,
[CombGrossIncome] [float] NULL,
[CombTotalIncome] [float] NULL,
[MonthlyDebtTotal] [float] NULL,
[DTIPreAssetDepletion] [float] NULL,
[DTIPostAssetDepletion] [float] NULL,
[RtFullyIndexed] [float] NULL,
[QualificationMethod] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PctDownPmtBorrFunds] [float] NULL,
[AVMProviderName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AVMConfidence] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AVMConfidence2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalValueCurr] [float] NULL,
[AppraisalTypeCurr] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTIFront] [float] NULL,
[CapitalizedAmt] [float] NULL,
[BalDeferred] [float] NULL,
[RtCurrPreMod] [float] NULL,
[PmtCurrPreMod] [float] NULL,
[RtFloorFirstPreMod] [float] NULL,
[RtCapPeriodicPreMod] [float] NULL,
[RtResetDtNextPreMod] [datetime] NULL,
[TermIOPreMod] [int] NULL,
[BalPrinForgivenMod] [float] NULL,
[BalIntForgivenMod] [float] NULL,
[NumModifications] [int] NULL,
[RealEstateInterest] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnershipStructure] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HUDCompliantFlag] [int] NULL,
[ManInvoiceGross] [float] NULL,
[ManInvoiceNet] [float] NULL,
[LTIGross] [float] NULL,
[LTINet] [float] NULL,
[Manufacturer] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModelName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DownPmtSrc1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommunityLenderFlag] [int] NULL,
[DefinedUWCriteriaFlag] [int] NULL,
[ChattelFlag] [int] NULL,
[CBSACode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBSATitle] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameMid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameMidCb] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelfEmployedFlagCb] [int] NULL,
[MaritalStatus] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatusCb] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderCb] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AgeCb] [int] NULL,
[BKChapter] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicationDt] [date] NULL,
[BorrPriorDelq120] [int] NULL,
[BorrPriorDelq120NR] [int] NULL,
[RtTeaser] [float] NULL,
[DelqReportedDt] [date] NULL,
[FCDischargeDt] [date] NULL,
[FHACaseNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetirementAssets] [float] NULL,
[DTIStressed] [float] NULL,
[APR] [float] NULL,
[DocTypeDetail] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BalEscrow] [float] NULL,
[QualifyingFICO] [int] NULL,
[Broker] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtAmt1Month] [float] NULL,
[NameFirstBroker] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIAmt1Month] [float] NULL,
[NameLastBroker] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtAmt2Month] [float] NULL,
[PIAmt2Month] [float] NULL,
[RtFloorLife] [float] NULL,
[DelqInterestMod] [float] NULL,
[PmtAmt3Month] [float] NULL,
[AppraiserCompany] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIAmt3Month] [float] NULL,
[AppraiserNameFirst] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtAmt4Month] [float] NULL,
[AppraiserNameLast] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIAmt4Month] [float] NULL,
[AppraiserLicNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtAmt5Month] [float] NULL,
[AppraiserLicExpDt] [date] NULL,
[PIAmt5Month] [float] NULL,
[PayHistFlag] [int] NULL,
[PmtAmt6Month] [float] NULL,
[PIAmt6Month] [float] NULL,
[PmtDueDtNext] [datetime] NULL,
[BPODt] [datetime] NULL,
[PmtAmt7Month] [float] NULL,
[PIAmt7Month] [float] NULL,
[PropertyVacantFlag] [int] NULL,
[PmtAmt8Month] [float] NULL,
[PropertyListedFlag] [int] NULL,
[FCSaleDt] [date] NULL,
[PIAmt8Month] [float] NULL,
[BKFilingDt] [date] NULL,
[PmtAmt9Month] [float] NULL,
[NegamAmt] [float] NULL,
[PIAmt9Month] [float] NULL,
[PmtAmt10Month] [float] NULL,
[RtTeaserEndDt] [date] NULL,
[PIAmt10Month] [float] NULL,
[Race] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtAmt11Month] [float] NULL,
[Racecb] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocTypeAppr] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIAmt11Month] [float] NULL,
[BalCorpAdvTotal] [float] NULL,
[PmtAmt12Month] [float] NULL,
[DocTypeTitle] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIAmt12Month] [float] NULL,
[AssetVerifFlag] [int] NULL,
[FBFlag] [int] NULL,
[PayHistStartMonth] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SNDReason] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BrokerComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CureReasonMod] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrepayPenaltyDesc] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderLoanID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TapeComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropTaxAmt] [float] NULL,
[ExceptionLevel] [int] NULL,
[EmploymentFlag] [int] NULL,
[IncomeTotal] [float] NULL,
[CombOtherIncome] [float] NULL,
[QMResidIncome] [float] NULL,
[EmploymentFlagcb] [int] NULL,
[FICOModelType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICOModelTypecb] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Appraiser] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Appraiser2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DownPmtAmt1] [float] NULL,
[BalEscrowOrig] [float] NULL,
[RtRoundingFlag] [int] NULL,
[LPMI] [float] NULL,
[TILRegZTotalPointsandFees] [float] NULL,
[HPMLFlag] [int] NULL,
[SvcTransferDt] [datetime] NULL,
[EligibilityWaiverFlag] [int] NULL,
[BorrPriorDelq30NR2yr] [int] NULL,
[BorrPriorDelq60NR2yr] [int] NULL,
[BorrPriorDelq90NR2yr] [int] NULL,
[DOB] [datetime] NULL,
[Ethnicity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtDebtOther] [float] NULL,
[HousingExpense] [float] NULL,
[DOBcb] [datetime] NULL,
[QMDesignation] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QMDesignationOrig] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [int] NULL,
[AgeCb2] [int] NULL,
[AgeCb3] [int] NULL,
[AssetVerifLevelCb2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetVerifLevelCb3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICODtCb] [datetime] NULL,
[FICODtCb2] [datetime] NULL,
[FICODtCb3] [datetime] NULL,
[FirstTimeBuyerFlagCb] [int] NULL,
[FirstTimeBuyerFlagCb2] [int] NULL,
[FirstTimeBuyerFlagCb3] [int] NULL,
[YearsAtResidenceCb] [int] NULL,
[YearsAtResidenceCb2] [int] NULL,
[YearsAtResidenceCb3] [int] NULL,
[CashTxfrAtClosing] [float] NULL,
[FICO1Cb2] [int] NULL,
[FICO1Cb3] [int] NULL,
[FICO2Cb2] [int] NULL,
[FICO2Cb3] [int] NULL,
[FICO3Cb2] [int] NULL,
[FICO3Cb3] [int] NULL,
[IncomeGrossCb2] [float] NULL,
[IncomeGrossCb3] [float] NULL,
[IncomeBonus] [float] NULL,
[IncomeBonusCb] [float] NULL,
[IncomeBonusCb2] [float] NULL,
[IncomeBonusCb3] [float] NULL,
[IncomeCommission] [float] NULL,
[IncomeCommissionCb] [float] NULL,
[IncomeCommissionCb2] [float] NULL,
[IncomeCommissionCb3] [float] NULL,
[SelfEmployedFlagCb2] [int] NULL,
[SelfEmployedFlagCb3] [int] NULL,
[EmploymentTypeCb] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentTypeCb2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentTypeCb3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentVerifTypeCb2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentVerifTypeCb3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameFirstCb2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameFirstCb3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtResetMoFirst] [int] NULL,
[GenderCb2] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderCb3] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GSEEligFlag] [int] NULL,
[SSNCb2] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSNCb3] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeVerifLevelCb2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeVerifLevelCb3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeVerifDescription] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeVerifDescriptionCb] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeVerifDescriptionCb2] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeVerifDescriptionCb3] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiscountAmt] [float] NULL,
[NameLastCb2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLastCb3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermNegamOrig] [int] NULL,
[AppraisalValueOrig] [float] NULL,
[IncomeOtherCb2] [float] NULL,
[IncomeOtherCb3] [float] NULL,
[PayHistoryMBA] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrepayPenaltyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecastFrequency] [int] NULL,
[AppraisalValue2] [float] NULL,
[AppraisalValue3] [float] NULL,
[AppraisalDtCurr] [datetime] NULL,
[AppraisalDt2] [datetime] NULL,
[AppraisalDt3] [datetime] NULL,
[AppraisalDescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalDescription2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalDescription3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalType2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalType3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginationLockDt] [datetime] NULL,
[SecFinAmt1] [float] NULL,
[EmploymentTypeSandP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentTypeSandPCb] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentTypeSandPCb2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentTypeSandPCb3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Form4506TFlagCb] [int] NULL,
[Form4506TFlagCb2] [int] NULL,
[Form4506TFlagCb3] [int] NULL,
[DTIOrig] [float] NULL,
[AppraisalVariance2] [float] NULL,
[AppraisalVariance3] [float] NULL,
[EmployedInField] [float] NULL,
[EmployedInFieldCb] [float] NULL,
[EmployedInFieldCb2] [float] NULL,
[EmployedInFieldCb3] [float] NULL,
[EmploymentLengthCb2] [float] NULL,
[EmploymentLengthCb3] [float] NULL,
[LoanFileReceivedDt] [datetime] NULL,
[ReviewTypeVendor] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalReceivedDt] [datetime] NULL,
[InsuranceAmt] [float] NULL,
[NegamCap] [float] NULL,
[ReviewType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IncomeWage] [float] NULL,
[IncomeWageCb] [float] NULL,
[CurrOtherMonthPmt] [float] NULL,
[DOBCb2] [date] NULL,
[EthnicityCb2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RaceCb2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICOModelTypeCb2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeWageCb2] [float] NULL,
[DOBCb3] [date] NULL,
[EthnicityCb3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RaceCb3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICOModelTypeCb3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeWageCb3] [float] NULL,
[EthnicityCb] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisbursementDt] [date] NULL,
[InitialResultsDt] [date] NULL,
[FinalResultsDt] [date] NULL,
[LastSellerResponseDt] [date] NULL,
[LastSellerResponseReqDt] [date] NULL,
[PriorOverallLevelVendor] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraiserCity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MonthsAssetBankStatementCb] [int] NULL,
[AppraiserState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IdentityVerifSrcType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IdentityVerifSrcTypeCb] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPATaxRtnReviewed] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPATaxRtnReviewedCb] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeVerifMonthsCnt] [int] NULL,
[IncomeVerifMonthsCntCb] [int] NULL,
[InvestorCommitmentIdentifier] [int] NULL,
[MonthsAssetBankStatement] [int] NULL,
[TransactionID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClosingCostFund1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FloodCertNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CombCommissionIncome] [float] NULL,
[CombBonusIncome] [float] NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [lms].[svDD] ADD CONSTRAINT [pk_svdd] PRIMARY KEY CLUSTERED  ([svDD_Key]) ON [PRIMARY]
GO
