CREATE TABLE [lms].[svDDEx]
(
[svDDEx_Key] [bigint] NOT NULL IDENTITY(1, 1),
[svDDEx_ID] [numeric] (10, 0) NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[svDDID] [numeric] (10, 0) NOT NULL,
[Code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StatusDetail] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsOfDt] [datetime] NOT NULL,
[Type] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueOrig] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueRevised] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reviewer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [xml] NULL,
[Datasource] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Username] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Timestamp] [datetime] NULL,
[ProviderIdentifier] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellerDisposition] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellerComments] [xml] NULL,
[OverallGrade] [int] NULL,
[MoodysGrade] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SandPGrade] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FitchGrade] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissingDocFlag] [int] NULL,
[CurableFlag] [int] NULL,
[CureText] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConclusionComments] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocUploadStatus] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverallGradeVendor] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommentsText] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsernameAsOf] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TimestampAsOf] [datetime] NOT NULL,
[UsernameINS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TimestampINS] [datetime] NOT NULL,
[TimestampAsOfVendor] [datetime] NULL,
[ClearDt] [date] NULL,
[WaiveDt] [date] NULL,
[Category] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanStatus] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompensatingFactors] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorStatus] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CloseDt] [date] NULL,
[VendorSatisfiedFlag] [int] NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [lms].[svDDEx] ADD CONSTRAINT [pk_svddex] PRIMARY KEY CLUSTERED  ([svDDEx_Key]) ON [PRIMARY]
GO
