CREATE TABLE [lms].[prAcq]
(
[prAcq_Key] [bigint] NOT NULL IDENTITY(1, 1),
[LoanID] [numeric] (10, 0) NOT NULL,
[AcqPoolID] [numeric] (10, 0) NULL,
[BATCH_ID] [bigint] NOT NULL,
[LAST_MODIFIED_ON] [datetime] NOT NULL,
[LAST_MODIFIED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_CURRENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DELETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FollowUp] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusDetail] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [xml] NULL,
[Datasource] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Username] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Timestamp] [datetime] NULL,
[MatchKey] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TradingAccount] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceBid] [float] NULL,
[AccruedIntAmt] [float] NULL,
[FundingType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceStl] [float] NULL,
[OtherFeeAmt] [float] NULL,
[BalCurrStl] [float] NULL,
[SvcTransferDt] [datetime] NULL,
[SvcTransferStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsOfDt] [datetime] NULL,
[StatusBID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusDetailBID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsernameBID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimestampBID] [datetime] NULL,
[StatusDD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusDetailDD] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsernameDD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimestampDD] [datetime] NULL,
[PayStatusOTS] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaidToDt] [datetime] NULL,
[PmtDueDtNext] [datetime] NULL,
[Repline] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Channel] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SettleDt] [datetime] NULL,
[TradeDt] [datetime] NULL,
[ServicingRights] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Desk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditGradeCalc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditGradeTrader] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditGradeFinal] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SvcInstructions] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOSStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockComment] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockExpirationDt] [datetime] NULL,
[LockExtensionDt] [datetime] NULL,
[PriceBaseBid] [float] NULL,
[PriceAdjBid] [float] NULL,
[LockProgram] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockPeriod] [int] NULL,
[LockWithdrawlDt] [datetime] NULL,
[ProgramID] [numeric] (10, 0) NULL,
[BalEscrowAdv] [float] NULL,
[BalOtherAdv] [float] NULL,
[PmtInstrID] [numeric] (10, 0) NULL,
[SettleDtOrig] [datetime] NULL,
[AccruedIntRt] [float] NULL,
[PriceAdjPairOff] [float] NULL,
[PriceMax] [float] NULL,
[RtCurrBuyUp] [float] NULL,
[RtCurrBuyDown] [float] NULL,
[RtMarginBuyUp] [float] NULL,
[RtMarginBuyDown] [float] NULL,
[CUSIP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSIPDescription] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExitBucketExp] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccruedIntDays] [int] NULL,
[LienPositionBid] [int] NULL,
[BalloonFlagBid] [int] NULL,
[BalOrigBid] [float] NULL,
[BalCurrBid] [float] NULL,
[TermOrigBid] [int] NULL,
[TermIOOrigBid] [int] NULL,
[PrepayPenaltyPeriodBid] [int] NULL,
[RtAdjustableFlagBid] [int] NULL,
[RtCurrBid] [float] NULL,
[RtMarginBid] [float] NULL,
[RtResetDtFirstBid] [datetime] NULL,
[RtIndexBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTVBid] [float] NULL,
[CLTVBid] [float] NULL,
[FICOBid] [int] NULL,
[DTIBid] [float] NULL,
[DocTypeBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurposeBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyTypeBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccupancyBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateBid] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipBid] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceBaseStl] [float] NULL,
[PriceAdjStip] [float] NULL,
[LatestFlag] [int] NULL,
[AgencyGrade] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccruedIntDaysAdd] [float] NULL,
[AccruedIntRtAdd] [float] NULL,
[AccruedIntAmtAdd] [float] NULL,
[AccruedSvcFeeAmt] [float] NULL,
[FloodFeeAmt] [float] NULL,
[TaxFeeAmt] [float] NULL,
[PaidToDtSched] [datetime] NULL,
[FundingAmt] [float] NULL,
[PayStatusMBA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceAdjBuyUpDown] [float] NULL,
[SvcFeePtsStl] [float] NULL,
[SvcFeeAmtStl] [float] NULL,
[SvcFeePrim] [float] NULL,
[SvcFeeStep] [float] NULL,
[SvcFeeStepDt] [datetime] NULL,
[PmtCurrStl] [float] NULL,
[RtCurrStl] [float] NULL,
[BalActStl] [float] NULL,
[SalesPersonID] [numeric] (10, 0) NULL,
[CreditGradeCalcBid] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PkgCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseRate] [float] NULL,
[LoanTypeBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalValueBid] [float] NULL,
[CUSIPSvcStrip] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TradAccntSvcStrip] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceSRPStl] [float] NULL,
[RtSched] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductTypeBid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EPDProtectionDt] [datetime] NULL,
[PRProtectionDt] [datetime] NULL,
[PmtDueDtNextSched] [datetime] NULL,
[SvcTransferComments] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceAdjStl] [float] NULL,
[BuyDownDt] [datetime] NULL,
[BalEscrow] [float] NULL,
[BalArrears] [float] NULL,
[PricingGroupSeller] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDRiskCategory] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsernameBRD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtForexStl] [float] NULL,
[SNDReason] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayHistoryTapeBid] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockStatusTape] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockExtensionPeriod] [int] NULL,
[PairOffStatus] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockExpirationDtOrig] [datetime] NULL,
[LockExtensionCnt] [int] NULL,
[LockExtensionStatus] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileStatus] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceSRPBid] [float] NULL,
[PriceSRPBaseBid] [float] NULL,
[PriceSRPAdjBid] [float] NULL,
[PriceSRPBaseStl] [float] NULL,
[PriceSRPAdjStl] [float] NULL,
[REOFlagBid] [int] NULL,
[NRVBid] [float] NULL,
[REOFlagStl] [int] NULL,
[NRVStl] [float] NULL,
[PayHistoryMBABid] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayHistoryMBAStl] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayHistoryTapeStl] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TradeID] [numeric] (10, 0) NULL,
[ParticipationFlag] [int] NULL,
[ParticipationPct] [float] NULL,
[prAcq_ID] [numeric] (10, 0) NULL,
[LTVStl] [float] NULL,
[ProductTypeStl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyTypeStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccupancyStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitsBid] [int] NULL,
[UnitsStl] [int] NULL,
[OriginationDtBid] [datetime] NULL,
[OriginationDtStl] [datetime] NULL,
[StateStl] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocTypeStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLTVStl] [float] NULL,
[NumBorrowersBid] [int] NULL,
[NumBorrowersStl] [int] NULL,
[DTIStl] [float] NULL,
[IOFlagBid] [int] NULL,
[IOFlagStl] [int] NULL,
[PMICoverageBid] [float] NULL,
[PMICoverageStl] [float] NULL,
[IncomeGrossBid] [float] NULL,
[IncomeGrossStl] [float] NULL,
[PriorDelq30Bid] [int] NULL,
[PriorDelq30Stl] [int] NULL,
[TermIOOrigStl] [int] NULL,
[PrepayPenaltyTermBid] [float] NULL,
[PrepayPenaltyTermStl] [float] NULL,
[RtOrigBid] [float] NULL,
[RtOrigStl] [float] NULL,
[ZipStl] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtCapFirstBid] [float] NULL,
[RtCapFirstStl] [float] NULL,
[RtCapLifeBid] [float] NULL,
[RtCapLifeStl] [float] NULL,
[BalOrigStl] [float] NULL,
[TermAmortOrigBid] [int] NULL,
[TermAmortOrigStl] [int] NULL,
[LPMIBid] [float] NULL,
[LPMIStl] [float] NULL,
[RtIndexStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConvertibleFlagBid] [int] NULL,
[ConvertibleFlagStl] [int] NULL,
[ModifiedFlagBid] [int] NULL,
[ModifiedFlagStl] [int] NULL,
[RtLookbackPeriodBid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtLookbackPeriodStl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RtResetFrequencyBid] [int] NULL,
[RtResetFrequencyStl] [int] NULL,
[RtTeaserBid] [int] NULL,
[RtTeaserStl] [int] NULL,
[TeaserTermBid] [int] NULL,
[TeaserTermStl] [int] NULL,
[EPDClause] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRClause] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKClause] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligibleFlag] [int] NULL,
[CertifiedFlag] [int] NULL,
[EscrowAdvancePrice] [float] NULL,
[CorporateAdvancePrice] [float] NULL,
[InternalRiskScore] [float] NULL,
[AppraisalTypeBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimestampINS] [datetime] NOT NULL,
[UsernameINS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BalCorpRecovAdv] [float] NULL,
[BalCorpNonRecovAdv] [float] NULL,
[BalCorpAdvTotal] [float] NULL,
[IsLockedFlag] [int] NULL,
[PricingReqDt] [datetime] NULL,
[LockStatusDt] [datetime] NULL,
[ModelPullthroughPct] [float] NULL,
[ModelExposure] [float] NULL,
[PriceChngFromLock] [float] NULL,
[LockDt] [datetime] NULL,
[AmortTypeBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmortTypeStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BalCorpAdvTotalBid] [float] NULL,
[BalCorpAdvTotalStl] [float] NULL,
[BalCurrIntBid] [float] NULL,
[BalCurrIntStl] [float] NULL,
[BalCurrNonIntBid] [float] NULL,
[BalCurrNonIntStl] [float] NULL,
[BalEscrowBid] [float] NULL,
[BalEscrowStl] [float] NULL,
[BalloonFlagStl] [int] NULL,
[BankruptcyFlagBid] [int] NULL,
[BankruptcyFlagStl] [int] NULL,
[FICODtBid] [datetime] NULL,
[FICODtStl] [datetime] NULL,
[FICOStl] [int] NULL,
[ForeclosureFlagBid] [int] NULL,
[ForeclosureFlagStl] [int] NULL,
[LoanTypeStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaturityDtBid] [datetime] NULL,
[MaturityDtStl] [datetime] NULL,
[ModificationDtBid] [datetime] NULL,
[ModificationDtStl] [datetime] NULL,
[ModificationTypeBid] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModificationTypeStl] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayStatusMBABid] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayStatusMBAStl] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PMICompanyBid] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PMICompanyStl] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtCurrBid] [float] NULL,
[PmtDueDtNextBid] [datetime] NULL,
[PmtDueDtNextStl] [datetime] NULL,
[PmtResetDtNextBid] [datetime] NULL,
[PmtResetDtNextStl] [datetime] NULL,
[PriceMark] [float] NULL,
[RtResetDtNextBid] [datetime] NULL,
[RtResetDtNextStl] [datetime] NULL,
[LockStatusPrev] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsOfDtPrev] [datetime] NULL,
[NewCreditorLetterCreateDt] [datetime] NULL,
[NewCreditorLetterSentDt] [datetime] NULL,
[NewCreditorLetterType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastPricedDt] [datetime] NULL,
[DeliveryDt] [datetime] NULL,
[ApprovedDt] [datetime] NULL,
[LockExtensionFee] [float] NULL,
[LockExtensionFee2] [float] NULL,
[LockExtensionFee3] [float] NULL,
[LockExtensionPeriod2] [int] NULL,
[LockExtensionPeriod3] [int] NULL,
[LockExtensionDt2] [datetime] NULL,
[LockExtensionDt3] [datetime] NULL,
[LockExtensionStatus2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockExtensionStatus3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimestampAsOf] [datetime] NOT NULL,
[UsernameAsOf] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUSIPSRP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TradAccountSRP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeliveryFeeAmt] [float] NULL,
[PmtDueDtFirst] [datetime] NULL,
[LockDtOrig] [datetime] NULL,
[LockPeriodOrig] [int] NULL,
[LockPeriodPrior] [int] NULL,
[LockDtPrior] [datetime] NULL,
[LockExpirationDtPrior] [datetime] NULL,
[RelockFeeCurr] [float] NULL,
[RelockFeeTotal] [float] NULL,
[PriceBaseBidOrig] [float] NULL,
[PriceAdjBidOrig] [float] NULL,
[PriceBasePrior] [float] NULL,
[PriceRtSheetPrior] [float] NULL,
[LockWithdrawlDtPrior] [datetime] NULL,
[PriceRtSheet] [float] NULL,
[FeesTotal] [float] NULL,
[NetAccruedIntAmt] [float] NULL,
[PremiumOrDiscount] [float] NULL,
[RequestProgram] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsernameRequest] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsernameResponse] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligibilityWaiverStatus] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsernameAdj] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WaiverRequestDetails] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WaiverRequestDt] [datetime] NULL,
[WaiverResponseDt] [datetime] NULL,
[WaiverRequestResponse] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManualPriceAdj] [float] NULL,
[WaiverRequestDescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockCnt] [int] NULL,
[TradeAccTreatment] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FundingSchedRunDt] [datetime] NULL,
[EligibilityWaiverFlag] [int] NULL,
[FSApprovalDt] [datetime] NULL,
[FSApprovedBy] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurposeStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameFirst] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLast] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameFirstCb] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLastCb] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EscrowFlagBid] [int] NULL,
[EscrowFlagStl] [int] NULL,
[QualifyingFICOBid] [int] NULL,
[QualifyingFICOStl] [int] NULL,
[QMTypeBid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QMTypeStl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalValueStl] [float] NULL,
[CitizenshipResidencyBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyCbBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyCbStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyCb2Bid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyCb2Stl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyCb3Bid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitizenshipResidencyCb3Stl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermOrigStl] [int] NULL,
[BalLienJuniorBid] [float] NULL,
[BalLienJuniorStl] [float] NULL,
[CashOutAmtBid] [float] NULL,
[CashOutAmtStl] [float] NULL,
[SalePriceBid] [float] NULL,
[SalePriceStl] [float] NULL,
[OriginationChannel] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelfEmployedFlagBid] [int] NULL,
[SelfEmployedFlagStl] [int] NULL,
[FirstTimeBuyerFlagBid] [int] NULL,
[FirstTimeBuyerFlagStl] [int] NULL,
[EscrowTypeBid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EscrowTypeStl] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetsTotalBid] [float] NULL,
[AssetsTotalStl] [float] NULL,
[MonthReservesBid] [float] NULL,
[MonthReservesStl] [float] NULL,
[FICOCb2Bid] [int] NULL,
[FICOCb2Stl] [int] NULL,
[FICOCb3Bid] [int] NULL,
[FICOCb3Stl] [int] NULL,
[TradeCounterparty] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileReceivedDt] [date] NULL,
[Section404LetterSentDt] [date] NULL,
[PriceSRPTape] [float] NULL,
[PriceSRPPremiumTape] [float] NULL,
[DaysWaived] [int] NULL,
[RtParity] [float] NULL,
[PriceBidTape] [float] NULL,
[PriceStlTape] [float] NULL,
[RtAdjBid] [float] NULL,
[RtAdjStl] [float] NULL,
[BaseRateBid] [float] NULL,
[BaseRateStl] [float] NULL,
[RtParityBid] [float] NULL,
[RtParityStl] [float] NULL,
[MSRStrip] [float] NULL,
[ExcessStrip] [float] NULL,
[MSRSpread] [float] NULL,
[ExcessSpread] [float] NULL,
[EscrowSpread] [float] NULL,
[MSRBaseMult] [float] NULL,
[ExcessBaseMult] [float] NULL,
[MSRAdjMult] [float] NULL,
[ExcessAdjMult] [float] NULL,
[DeliveryDtAppraisal] [datetime] NULL,
[StatusDDAppraisal] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsernameDDAppraisal] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimestampDDAppraisal] [datetime] NULL,
[LOSStatusAsOfDt] [datetime] NULL,
[NAMESPACE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [lms].[prAcq] ADD CONSTRAINT [pk_pracq] PRIMARY KEY CLUSTERED  ([prAcq_Key]) ON [PRIMARY]
GO
